import './globals.css'

export const metadata = {
  title: 'Homepage aden',
  description: 'Generated by aden',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
